### ISSUE TITLE
[구현] Feature Engineering

### ISSUE THREAD

**Issue by Su-minn** [boostcampaitech3/final-project-level3-cv-05#3]
### 모델 학습을 위한 Feature Engineering prototype
- [x] prototype 

prototype 기한: ~ 2022-05-18

**Comment by sw930718** [comment]
추가 보완 내용 
- [x] 명함내 bbox간의 위치 파악을 위해, 동일 명함내 카테고리 bbox의 중심점 feature 생성   

기한: ~ 2022.06.09
